title: React Jekyll Site
email: your-email@example.com
description: >-
  A React application built with Jekyll for GitHub Pages
baseurl: ""
url: ""

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/